select * from T_CART;

select *
from T_CART A, T_CART_SELL_PRODUCT B, T_SELL_PRODUCT C, T_SELL_ITEM_PAGE D, T_SELL_PAGE E,
     T_SELL_IMAGE F, T_PRODUCT G
WHERE A.CART_NO = B.CART_NO AND B.SELL_PRODUCT_ID = C.SELL_PRODUCT_ID AND C.SELL_PRODUCT_ID = D.SELL_PRODUCT_ID
  AND C.PRODUCT_CODE = G.PRODUCT_CODE
  AND D.SELL_PAGE_NO = E.SELL_PAGE_NO AND E.SELL_PAGE_NO = F.SELL_PAGE_NO;


commit;


-- 기존 테이블 데이터 삭제 후
-- T_CART EMP_NO UNIQUE KEY 등록

delete from T_CART;
delete from T_CART_SELL_PRODUCT;
delete from T_ORDER;

ALTER TABLE T_CART ADD CONSTRAINT T_CART_UK UNIQUE(EMP_NO);


ALTER TABLE T_CART_SELL_PRODUCT MODIFY DELIVERY_PRICE DEFAULT 0;

INSERT INTO T_CART_SELL_PRODUCT
( CART_NO, SELL_PRODUCT_ID, CART_AMOUNT, DELIVERY_PRICE)
VALUES ('CR000055', 'SP15', 2, DEFAULT);

SELECT * FROM T_CART_SELL_PRODUCT;

COMMIT;


