select * from T_CART;

select *
from T_CART A, T_CART_SELL_PRODUCT B, T_SELL_PRODUCT C, T_SELL_ITEM_PAGE D, T_SELL_PAGE E,
     T_SELL_IMAGE F, T_PRODUCT G
WHERE A.CART_NO = B.CART_NO AND B.SELL_PRODUCT_ID = C.SELL_PRODUCT_ID AND C.SELL_PRODUCT_ID = D.SELL_PRODUCT_ID
  AND C.PRODUCT_CODE = G.PRODUCT_CODE
  AND D.SELL_PAGE_NO = E.SELL_PAGE_NO AND E.SELL_PAGE_NO = F.SELL_PAGE_NO;


commit;


-- 기존 테이블 데이터 삭제 후
-- T_CART EMP_NO UNIQUE KEY 등록

delete from T_CART;
delete from T_CART_SELL_PRODUCT;
delete from T_ORDER;

ALTER TABLE T_CART ADD CONSTRAINT T_CART_UK UNIQUE(EMP_NO);


ALTER TABLE T_CART_SELL_PRODUCT MODIFY DELIVERY_PRICE DEFAULT 0;

INSERT INTO T_CART_SELL_PRODUCT
( CART_NO, SELL_PRODUCT_ID, CART_AMOUNT, DELIVERY_PRICE)
VALUES ('CR000055', 'SP15', 2, DEFAULT);

SELECT * FROM T_CART_SELL_PRODUCT;

COMMIT;

INSERT INTO T_ORDER
(ORDER_NO, ORDER_DATE, TOTAL_PRICE, DELIVERY_TYPE, EMP_NO)
VALUES
    ('O' || LPAD(SEQ_ORDER_NO.nextval, 6, '0'), SYSDATE, 5000000, '일반주문', 'E00006');
INSERT INTO T_ORDER
(ORDER_NO, ORDER_DATE, TOTAL_PRICE, DELIVERY_TYPE, EMP_NO)
VALUES
    ('O' || LPAD(SEQ_ORDER_NO.nextval, 6, '0'), SYSDATE, 1000000, '일반주문', 'E00043');
INSERT INTO T_ORDER
(ORDER_NO, ORDER_DATE, TOTAL_PRICE, DELIVERY_TYPE, EMP_NO)
VALUES
    ('O' || LPAD(SEQ_ORDER_NO.nextval, 6, '0'), SYSDATE, 5000000, '반품', 'E00006');


COMMIT;

SELECT * FROM T_ORDER;


INSERT INTO T_PRODUCT_ORDER
(PRODUCT_ORDER_NO, ORDER_NO, SELL_PRODUCT_ID, PRODUCT_ORDER_AMOUNT,
 PRODUCT_ORDER_PRICE, DELIVERY_DATE)
VALUES ('PO' || LPAD(SEQ_PRODUCT_ORDER_NO.NEXTVAL, 6, '0'),
        'O000001', 'SP19', 1, 3000000, SYSDATE );

INSERT INTO T_PRODUCT_ORDER
(PRODUCT_ORDER_NO, ORDER_NO, SELL_PRODUCT_ID, PRODUCT_ORDER_AMOUNT,
 PRODUCT_ORDER_PRICE, DELIVERY_DATE)
VALUES ('PO' || LPAD(SEQ_PRODUCT_ORDER_NO.NEXTVAL, 6, '0'),
        'O000001', 'SP25', 1, 2000000, SYSDATE );

INSERT INTO T_PRODUCT_ORDER
(PRODUCT_ORDER_NO, ORDER_NO, SELL_PRODUCT_ID, PRODUCT_ORDER_AMOUNT,
 PRODUCT_ORDER_PRICE, DELIVERY_DATE)
VALUES ('PO' || LPAD(SEQ_PRODUCT_ORDER_NO.NEXTVAL, 6, '0'),
        'O000002', 'SP25', 1, 1000000, SYSDATE );

COMMIT;

SELECT * FROM T_PRODUCT_ORDER;

INSERT INTO T_ORDER
(ORDER_NO, ORDER_DATE, TOTAL_PRICE, DELIVERY_TYPE, EMP_NO)
VALUES
    ('O' || LPAD(SEQ_ORDER_NO.nextval, 6, '0'), SYSDATE, 254500, '일반주문', 'E00014');
INSERT INTO T_ORDER
(ORDER_NO, ORDER_DATE, TOTAL_PRICE, DELIVERY_TYPE, EMP_NO)
VALUES
    ('O' || LPAD(SEQ_ORDER_NO.nextval, 6, '0'), SYSDATE, 999990, '일반주문', 'T00016');


INSERT INTO T_PRODUCT_ORDER
(PRODUCT_ORDER_NO, ORDER_NO, SELL_PRODUCT_ID, PRODUCT_ORDER_AMOUNT,
 PRODUCT_ORDER_PRICE, DELIVERY_DATE)
VALUES ('PO' || LPAD(SEQ_PRODUCT_ORDER_NO.NEXTVAL, 6, '0'),
        'O000004', 'SP54', 1, 100000, SYSDATE );
INSERT INTO T_PRODUCT_ORDER
(PRODUCT_ORDER_NO, ORDER_NO, SELL_PRODUCT_ID, PRODUCT_ORDER_AMOUNT,
 PRODUCT_ORDER_PRICE, DELIVERY_DATE)
VALUES ('PO' || LPAD(SEQ_PRODUCT_ORDER_NO.NEXTVAL, 6, '0'),
        'O000004', 'SP20', 1, 154500, SYSDATE );
INSERT INTO T_PRODUCT_ORDER
(PRODUCT_ORDER_NO, ORDER_NO, SELL_PRODUCT_ID, PRODUCT_ORDER_AMOUNT,
 PRODUCT_ORDER_PRICE, DELIVERY_DATE)
VALUES ('PO' || LPAD(SEQ_PRODUCT_ORDER_NO.NEXTVAL, 6, '0'),
        'O000005', 'SP85', 1, 999990, SYSDATE );

COMMIT;

SELECT * FROM T_PRODUCT_ORDER;


